### PR TITLE
Add support for extension attributes

### LINKED ISSUE #162: Request to add support for custom claim identifiers in AzureCP other than default
My company is trying to integrate Azure AD federated authentication in its SharePoint 2019 farm. Current we use custom user identifier in on-prem AD like "EmpID". The old ADFS server will be decommissioned soon and we will transition to Azure AD federated authentication.

We have this custom property synced with the AzureAD too and currently can federate authentication using Azure AD Enterprise app without AzureCP. We plan to use AzureCP fo resolve user for better experience. But resolving user using EmpID does not work and thus setting permission via same fails.

We also have restrictions getting Application permission GroupMember.Read.All and User.Read.All in our tenant. So, is there a way we can change the application to use Delegate permissions?

Summarizing the changes we look forward to are listed below. We can also contribute if needed to bring below enhancements.
1. Add support for non-standard user claim identifier like EmpID.
2. Add support to resolve user with their additional properties like EmpID.
3. Add support to use delegated permission for resolving user/groups(GroupMember.Read.All and User.Read.All)

### PR DESCRIPTION
**Pull request by andikrueger**
This PR will fix #162 and add a new capability to add custom claims. At the moment, the changes are tested with one tenant, but should work with more than one tenant as well. 

@Yvand Could you have a look at the changes, if there is any thing that could break other parts of the solution? Thanks!

### CODE REVIEW

**Comment by andikrueger** [comment]
Just to note, there is still an issue within the regular people picker within a site. It shows a different number of results (visible vs. count). I'll have a look at this.

**Comment by Yvand** [comment]
@andikrueger thank you very much for your contribution, I will take a close look and keep you posted

**Comment by andikrueger** [comment]
At the moment, we do one further issues: Group Claims will not be available in CA; In all other webapps they are there.

**Comment by Yvand** [comment]
@andikrueger in some places only users are accepted, e.g. in site collection administrators page you can add only users.
Does it match what you noticed?

**Comment by andikrueger** [comment]
Actually yes. So this is not a bug.

**Comment by Yvand** [comment]
@andikrueger before reviewing your PR I had totally no idea about the extension attributes feature, but it's actually a nice feature in Azure AD, and the integration in AzureCP is much easier than I feared.
Today I tested this feature on my tenant, next week I'll review in depth the PR itself and come back to you

**Comment by andikrueger** [comment]
Let me know, if you need any assistance!

**Comment by Yvand** [comment]
@andikrueger I spent some time on this today, so far it looks great, but there is 1 thing I was not able to do:
I configured my enterprise app to issue a claim with value `user.extensionattribute1`, but after sign-in as a user that this extension attribute set, this claim is missing in the SAML token.
Did you try with a SAML or an ID token ?

**Comment by andikrueger** [comment]
We did some testing in regards to SAML tokens and I did not get any negative feedback. Did you configure your claims here:

image

**Comment by Yvand** [comment]
Yes I think I have the proper config:
image

For the test I added well-known email claim type with the same value, but both claims email/type1 are missing in the token. It is possible I'm doing a dumb mistake, I think I'll wait tomorrow to take a fresh look at this :) 
I keep you posted

**Comment by Yvand** [comment]
I must be missing something.
My user has extensionAttribute1 set:

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(id,displayName,userPrincipalName,extension_db1e6850023e4d439ebc39871218d32e_extensionAttribute1)/$entity",
    "displayName": "Pradeep Gupta",
    "userPrincipalName": "xPradeepG@M365x997769.OnMicrosoft.com",
    "extension_db1e6850023e4d439ebc39871218d32e_extensionAttribute1": "value1"
}
```

I use this extensionAttribute1 in my app:
image

And yet the claims are not included in the token.
If I change the claim type settings to issue attribute `user.mail` or `user.userprincipalname` instead, then it is included as expected in the SAML token. What am I missing?

**Comment by andikrueger** [comment]
Did you configure this claim within the trusted token issuer as well?

**Comment by Yvand** [comment]
@andikrueger I think I understand the issue:
I created a specific app registration to create my extension attribute.
Based on [this doc](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-schema-extensions#emitting-claims-with-data-from-directory-extension-attributes-created-for-an-application-using-graph-or-powershell), to use this extension attribute in another app (my enterprise app for SPS SAML), I need to create a [claims mapping policy](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping).

But I have no idea how to do that for a SAML token.
What app identity did you use to create your extension attribute?

**Comment by andikrueger** [comment]
@julmsy do you remember, what kind of additional steps we did?

I used the AzureCP app to register the extension attributes. In our default environment the extensions are created by AD connect.

**Comment by julmsy** [comment]
Just noticed, but there is a double '/' in the path your Claim type.
`http://schemas.yvand.org//claims/type1`
This could be an issue if the Claim Type is not EXACTLY what is expected.
The Claim type must also be configured on the SPTrustedIdentityTokenIssuer object, otherwise it is not present in the Token.

Other than that, nothing really special in term of configuration:
- Created the Enterprise App on Azure AD
- Configured the SAML sign-on method
- Configuration on SharePoint to switch from ADFS to AAD
- Configuration of AzureCP solution (could be linked with the App Registration created by the Enterprise App, or a dedicated App Registration, I've tested both scenarios).
-

**Comment by Yvand** [comment]
So this turned out to be very much more complicated than I anticipated. In short:

1. Create a dedicated app registration; and use its ID to [add an extension attribute](https://learn.microsoft.com/en-us/graph/api/application-post-extensionproperty?view=graph-rest-1.0&tabs=http):
<https://graph.microsoft.com/v1.0/applications/{{applicationObjectId}}/extensionProperties>

2. [Create a claimsMappingPolicy](https://learn.microsoft.com/en-us/graph/api/claimsmappingpolicy-post-claimsmappingpolicies?view=graph-rest-1.0&tabs=http) that list all the claims that will be added to the SAML token:
<https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies>

3. [Assign that claimsMappingPolicy](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-1.0&tabs=http) to the SharePoint enterprise application:
<https://graph.microsoft.com/v1.0/servicePrincipals(appId='{appId}')/claimsMappingPolicies/$ref>

Steps 2 and 3 are somewhat explained in [this article](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-schema-extensions#emitting-claims-with-data-from-directory-extension-attributes-created-for-an-application-using-graph-or-powershell), but it is omitting a lot of information I had to dig in myself.

Also, none of these steps can be done from the AAD portal, I did everything using Postman.
@andikrueger, I'm pretty sure that your extension attribute is not included in the SAML token created by Azure AD, since the screenshot you copied has no effect on extension attributes (which is very confusing since the UI lets you think that everything is alright)

**Comment by andikrueger** [comment]
Good find and thank you for outlining. We did not need to configure anything additionally as we used the AD Connect extension Attributes for testing:

> Once a directory extension attribute created via AD Connect is in the directory, it will show in the SAML SSO claims configuration UI.

https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-schema-extensions#emitting-claims-with-data-from-directory-extension-attributes-created-with-ad-connect

This obviously only applies to AD connect and not any other application.

**Comment by Yvand** [comment]
@andikrueger indeed, you mentioned it earlier but I missed that point, thanks!

**Comment by Yvand** [comment]
@andikrueger I tested it on my dev env and it works great.
1 remark regarding the name of variable `ADConnectClientId`:
It totally makes sense in your scenario, but it needs to be meaningful also for the scenario where Azure AD Connect is not used (which is how I tested extension attributes), so we need to rename it.

I though about `ExtensionAttributesApplicationId`.
Thoughts ?

**Comment by andikrueger** [comment]
The name of the new attribute should not matter. There is just one minor thing I'd like to point out. If we would go for any other naming, this might imply that there would be the option to have multiple applications within the same tenant that would add additional extensions.

**Comment by andikrueger** [comment]
@Yvand I'm still facing one issue. The counter for results and the list of results do not match. I was able to trace it to the method 'FillSearch' in AzureCP.cs (starting at line 1022)

This screenshot is within people picker in SharePoint:

image

This one shows the collection holding two elements, but the one caused by the extension attribute not showing up:

image

**Comment by Yvand** [comment]
@andikrueger @julmsy FYI I've been working on moving the CI pipeline to GitHub actions, as a replacement of Azure DevOps.
As I was not even sure if it is possible (building wsp solutions from GitHub actions is very much undocumented) and I did not want to do tests on this repo, I tested on [this repo](https://github.com/Yvand/SPBypassLoginPage/pull/10).
I'm finished now so I'll do the same here, which means that soon you'll be able to download the artifact, signed with the regular key

**Comment by Yvand** [comment]
@andikrueger I was not able to repro the issue you mentioned with a result not displayed.

But now that I think about it, there is something wrong with current implementation.
IMO the extension attribute should be considered as a group, since multiple users can have the same value for it.
In my environment, I created extension attribute "extensionAttribute1", and set it with value "value1" on 2 users.
Then in SharePoint I add a permission for "value1", and I do intend that all users which have this value can access the resource.

But I blocked the max number of group claim types to 1 through [this property](https://github.com/Yvand/AzureCP/blob/dev/AzureCP/AzureCPConfig.cs#L55).
I will test to change it and see what happens

**Comment by andikrueger** [comment]
This sounds very reasonable.

Even though I see the value of users being display in case of the extension attribute is matched. 

It’s more convenient to treat the extension attributes as group claims

**Comment by Yvand** [comment]
It's going to be complicated. For simplicity, a long time ago I decided to merge 2 settings:
- The Azure AD directory object type: `User` or `Group`
- The SharePoint [`PickerEntity.EntityType`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.webcontrols.pickerentity.entitytype?view=sharepoint-server): In theory any value in [class SPClaimEntityTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.claims.spclaimentitytypes?view=sharepoint-server), but in AzureCP, only `User` or `FormsRole`.

So [my simplification](https://github.com/Yvand/AzureCP/blob/dev/AzureCP/AzureCP.cs#L574) is on the ClaimTypeConfig:
- If Azure AD directory object type is "User": SharePoint PickerEntity.EntityType is `SPClaimEntityTypes.User`
- If Azure AD directory object type is "Group": SharePoint PickerEntity.EntityType is `SPClaimEntityTypes.FormsRole`

But what we want here is a property on Azure AD directory object "User" be considered as a `SPClaimEntityTypes.FormsRole`, and it is not possible as is.
I need to think more on this to understand if this is truly important to manage this properly.

At least this matters when building the filter:
In my env, my test extension attribute, targets only to `User`.
But if the $filter for type `Group` contains the extension attribute, Azure AD throws error `Property 'extension_db1e6850023e4d439ebc39871218d32e_extensionAttribute1' does not exist as a declared property or extension property.`

**Comment by andikrueger** [comment]
Thanks for the summary. This helps a lot. 

I’ll have a look at the code too, tomorrow. 

The part about the Group and the extension attribute is kind of expected. Within azure the extension attributes are created on an object basis. You would need to create the extension for the app on the group object within AAD as well. It might be good to do the search only if there is a claim registered for this kind of object. Looks like I missed this in the first place…

**Comment by andikrueger** [comment]
@Yvand I spend the last hour reading code and am wondering if it would be sufficient to extend the condition with something like this:

IF Type == User && not extensionAtrribute ? User : GroupClaim

I'll rune some test with it

**Comment by Yvand** [comment]
I just pushed [a commit](https://github.com/Yvand/AzureCP/pull/174/commits/e30a8c7a53856ec63c9f5d8d3bb99b13fee94077) that adds property `SharePointEntityType` and that can be set to `User` or `FormsRole`, to override the default association AAD User = user permission and AAD Group = group permission.

It needs to be set through PowerShell:

```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$ctconf = $config.ClaimTypes.GetByClaimType("http://schemas.yvand.org/claims/type1")
$ctconf.SharePointEntityType = "FormsRole"
$config.Update()
```

With the retro-compatibility in mind, the logic is that if this property is not set, this has no impact on existing configurations

**Comment by andikrueger** [comment]
I'll do some testing :)

**Comment by andikrueger** [comment]
image

image

Above there a two Screenshots after configuring the Claim to be of type FromsRole. This did not the trick. 

The second value within my list of possible values should be the "Group of Users with the Extension Attribute Value of 'Test'"

**Comment by Yvand** [comment]
Can you confirm in AzureCP logs if it returns only 1 entity (instead of 2) ?

**Comment by andikrueger** [comment]
Will do so. Last time I checked two values were returned. The search for a user yields also the extension attribute. 

I do have two users:

test 1@something.onMicrosoft.com

another user with the extension attribute and the value test. 

Both users will be returned. One should result in a user object. The other user should show up either as user or as a group

**Comment by andikrueger** [comment]
I just had a look at ULS log:

```
02/24/2023 08:44:45.11	w3wp.exe (0x25BC)	0x2FB4	AzureCP	Lookup	1337	Medium	[AzureCP] Got 2 users/groups in 63 ms from '.onMicrosoft.com' with input 'test'	
02/24/2023 08:44:45.11	w3wp.exe (0x25BC)	0x3574	AzureCP	Lookup	1337	Verbose	[AzureCP] 2 entity(ies) to create after filtering	e84899a0-e35e-b0e7-5e95-04427007c671
02/24/2023 08:44:45.11	w3wp.exe (0x25BC)	0x3574	AzureCP	Claims Picking	1337	Verbose	[AzureCP] Added entity: display text: 'test1@s.onmicrosoft.com', claim value: 'test1@.onmicrosoft.com', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn'	e84899a0-e35e-b0e7-5e95-04427007c671
02/24/2023 08:44:45.11	w3wp.exe (0x25BC)	0x3574	AzureCP	Claims Picking	1337	Verbose	[AzureCP] Added entity: display text: '(Brand Code) Test', claim value: 'Test', claim type: 'http://.com/claims/brandcode'	e84899a0-e35e-b0e7-5e95-04427007c671
02/24/2023 08:44:45.11	w3wp.exe (0x25BC)	0x3574	AzureCP	Claims Picking	1337	Medium	[AzureCP] Returned 2 entities from input 'test'	e84899a0-e35e-b0e7-5e95-04427007c671

```

The entity type of the secon object would match the latest changes

image

There are two nodes created. One of them is the extension attribute.

image

Whereas it is working within central admin:

image

Any idea, what could cause this behaviour?

**Comment by andikrueger** [comment]
Some more information on this one: The key for the extension claim is null and Get-SPClaimTypeInformation does not list the claim for the extension.

**Comment by andikrueger** [comment]
Obviously, if there is no claim type mapping, no key will be generated and the object can't be added to the people picker...

Running:
```powershell
New-SPClaimTypeEncoding -ClaimType http://com/claims/brandcode -EncodingCharacter ([Convert]::ToChar(513))

Get-SPClaimTypeEncoding | ft @{Label="Character";Expression={[Convert]::ToInt32($_.EncodingCharacter)}}, ClaimType | ft -autosize

Character ClaimType
--------- ---------
      513 http://.com/claims/brandcode
       64 http://schemas.xmlsoap.org/ws/2005/05/identity/claims/otherphone
```

Was the final step needed.

**Comment by Yvand** [comment]
@andikrueger I just saw your commit https://github.com/Yvand/AzureCP/pull/174/commits/7d2e33ac143d51dbf4cc446482a7dea3a02a7882:
[`ClaimsProviderConstants.GroupClaimEntityType`](https://github.com/Yvand/AzureCP/blob/ef4586ba978d3d28523269bd70d4b5712d377944/AzureCP/AzureCPConfig.cs#L54) is set to `SPClaimEntityTypes.FormsRole` so this addition is not necessary.
Can you please revert the commit?
Do you have additional remarks/concerns on this PR? On my side, given the significant changes, I would like to run the unit tests on it before merging it, but I'm not ready yet to do it unfortunately

**Comment by andikrueger** [comment]
Just reverted the change. 

You can proceed to merge as the issues above are resolved. Maybe it's worth to add the New-SPClaimTypeEncoding to the documentation.

**Comment by andikrueger** [comment]
Just review the line mentioned. I think you did introduce this change.

**Pull request merged**
